---
- name: "Update apt cache & upgrade packages"
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: "Install basic utilities & fail2ban"
  apt:
    name:
      - git
      - curl
      - unzip
      - fail2ban
      - ufw
    state: present
    update_cache: yes

- name: "Ensure UFW allows SSH"
  ufw:
    rule: allow
    name: OpenSSH

- name: "Ensure UFW allows HTTP (port 80)"
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: "Ensure UFW allows HTTPS (port 443)"
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: "Enable UFW"
  ufw:
    state: enabled